services: 
  - type: web
    name: doc_convert
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: python main.py
    repo: https://github.com/luishcarreira/doc_convert.git
    branch: main
    region: oregon
    plan: free
    numInstances: 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db
          property: connectionString

databases:
  - name: postgres_db
  
